baseURL = "/"
languageCode = "en-us"
title = "Sebi Lozano"
theme = "aether"


[params]
brand = "sebi"
description = "The website's description"
homeimg = "/uploads/IMG_1117.png"
bgimg = "/uploads/IMG_1117.png"

